spaces = ' ' * 25
print ('%s 12 butt wynd' % spaces)
print('%s twinklebotom heath' % spaces)
print('%s west snoring' % spaces)
print()
print()
print('dear sir')
print()
print(' i wish to report that tiles are mission from the')
print('outside toilet roof.')
print('i think it was bad wind the other night that blew them away.')
print()
print('regards')
print("malcolm dithering")